#  spring.devtools.livereload.enabled=true
#    spring.datasource.url=jdbc:mysql://localhost:3306/hoanghacosmetic
#    spring.datasource.username=root
#    spring.datasource.password=123456
#    spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#    spring.jpa.show-sql=true
#    spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
#    spring.jpa.hibernate.ddl-auto=update
#    jwt.expiration=3600
#    jwt.secetKey=secetKey=Qc20ljRUvOqlXrrEolJRXyLaMBdX/qNh95MNk3nt618=

spring:
  devtools:
    livereload:
      enabled: true
  datasource:
    url: "jdbc:mysql://localhost:3306/hoanghacosmetic"
    username: "root"
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  security:
    saml2:
      relyingparty:
        registration:
          okta:
            assertingparty:
              metadata-uri: https://dev-55392673.okta.com/app/exkjq2fhwvMrODg7V5d7/sso/saml/metadata
            signing:
              credentials:
                - certificate-location: classpath:local.crt
                  private-key-location: classpath:local.key
            singlelogout:
              binding: POST
              response-url: "{baseUrl}/logout/saml2/slo"


jwt:
  expiration: 3600
  secetKey: secetKey=Qc20ljRUvOqlXrrEolJRXyLaMBdX/qNh95MNk3nt618=